remove yajl install

diff --git a/bin/make-kafkacat b/bin/make-kafkacat
--- a/bin/make-kafkacat
+++ b/bin/make-kafkacat
@@ -107,11 +107,11 @@ pushd $KAFKACAT_BUILD_DIR > /dev/null
 topic "Installing kafkacat dependencies..."
 
 github_download "edenhill/librdkafka" "master" "librdkafka"
-github_download "lloyd/yajl" "master" "libyajl"
+#github_download "lloyd/yajl" "master" "libyajl"
 
 build librdkafka "([ -f config.h ] || ./configure >> build.log) && make >> build.log && make DESTDIR=\"${PWD}/\" install >> build.log" || (echo "Failed to build librdkafka: bootstrap failed" | indent ; false)
 
-build libyajl "([ -f config.h ] || ./configure >> build.log) && make >> build.log && make DESTDIR=\"${PWD}/\" install >> build.log" || (echo "Failed to build libyajl: JSON support will probably be disabled" | indent ; true)
+#build libyajl "([ -f config.h ] || ./configure >> build.log) && make >> build.log && make DESTDIR=\"${PWD}/\" install >> build.log" || (echo "Failed to build libyajl: JSON support will probably be disabled" | indent ; true)
 
 popd > /dev/null
 
@@ -123,7 +123,7 @@ topic "Building kafkacat"
 export CPPFLAGS="${CPPFLAGS:-} -I$KAFKACAT_BUILD_DIR/usr/local/include"
 export LIBS="$(pkg_cfg_lib rdkafka) $(pkg_cfg_lib yajl)"
 export STATIC_LIB_rdkafka="$KAFKACAT_BUILD_DIR/usr/local/lib/librdkafka.a"
-export STATIC_LIB_yajl="$KAFKACAT_BUILD_DIR/usr/local/lib/libyajl_s.a"
+# export STATIC_LIB_yajl="$KAFKACAT_BUILD_DIR/usr/local/lib/libyajl_s.a"
 ./configure --prefix=$KAFKACAT_BUILD_DIR --enable-static --enable-json >> build.log
 make >> build.log
 
