mklove update to 05487e067ec4fb (for #70)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
 #
 
+BASHVER=$(expr ${BASH_VERSINFO[0]} \* 1000 + ${BASH_VERSINFO[1]})
+
+if [ "$BASHVER" -lt 3002 ]; then
+    echo "ERROR: mklove requires bash version 3.2 or later but you are using $BASH_VERSION ($BASHVER)"
+    echo "       See https://github.com/edenhill/mklove/issues/15"
+    exit 1
+fi
+
 MKL_CONFIGURE_ARGS="$0 $*"
 
 # Load base module
@@ -59,6 +67,8 @@ done
 ##
 ##
 
+_SAVE_ARGS="$*"
+
 # Parse arguments
 while [[ ! -z $@ ]]; do
     if [[ $1 != --* ]]; then
@@ -111,13 +121,9 @@ while [[ ! -z $@ ]]; do
     case $name in
         re|reconfigure)
             oldcmd=$(grep '^# configure exec: ' config.log | \
-                sed -e 's/^\# configure exec: //')
-            if [[ -z $oldcmd ]]; then
-                mkl_err "No previous execution found in config.log"
-                exit 1
-            fi
-            echo "Reconfiguring: $oldcmd"
-            exec $oldcmd
+                sed -e 's/^\# configure exec: [^ ]*configure\( \|$\)//')
+            echo "Reconfiguring: $0 $oldcmd"
+            exec $0 $oldcmd
             ;;
 
         list-modules)
@@ -177,13 +183,10 @@ fi
 
 
 # Create output files
-echo "# configure exec: $0 $*" >> $MKL_OUTDBG
+echo "# configure exec: $0 $_SAVE_ARGS" >> $MKL_OUTDBG
 echo "# On $(date)" >> $MKL_OUTDBG
 
 rm -f $MKL_OUTMK $MKL_OUTH
-mkl_write_mk "# Automatically generated by $0 $*"
-mkl_write_h "// Automatically generated by $0 $*"
-mkl_write_h "#pragma once"
 
 
 # Load cache file
